theme: jekyll-theme-cayman
title: Welcome to the Soaps And Love's homepage
description: Company dedicated to the manufacture of soaps, bath salts and handmade candles for the care of the skin and the bei
